FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    xz-utils \
    gdb-multiarch \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir gdbgui
RUN curl -qsL 'https://install.pwndbg.re' | sh -s -- -t pwndbg-gdb

WORKDIR /fatal_core_dump

COPY src/ /fatal_core_dump
COPY bin/airlock_ctrl /fatal_core_dump
COPY bin/core.dump /fatal_core_dump
