#FROM debian:bookworm-slim
FROM ubuntu:22.04


RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    util-linux \
    screen \
    gdb \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir pwntools

RUN echo '#!/bin/sh' > /entrypoint.sh \
    && echo 'echo "/fatal_core_dump/bin/core.dump" > /proc/sys/kernel/core_pattern' >> /entrypoint.sh \
    && echo 'ulimit -c unlimited' >> /entrypoint.sh \
    && echo 'exec "$@"' >> /entrypoint.sh \
    && chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
WORKDIR /fatal_core_dump
